# Generated by Django 5.2.11 on 2026-02-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valide", "valide"),
                            ("en_attente", "en_attente"),
                            ("suppr", "suppr"),
                        ],
                        default="valide",
                        max_length=16,
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medical.medication",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medical.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["patient"],
            },
        ),
    ]
